id: P4C07A5A0
initial_creation_type: input
source_metadata:
  title: Nāropa
  language: en
  description: 'Texts by the great siddha Nāropa (956–1040):'
  volume:
    8cdd41baa90c4fa2ae947459273576ba:
      title: Homage to Milarepa
      parent: Praise
created_at: '2022-03-01T02:19:01.808576'
last_modified_at: '2022-03-01T02:19:01.808583'
